# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-12 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=100)),
                ('num', models.IntegerField(verbose_name=1)),
            ],
        ),
        migrations.AlterField(
            model_name='imgs',
            name='imgname',
            field=models.CharField(max_length=1000),
        ),
    ]
