# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190112_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goodse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('num', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goodse'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usermode'),
        ),
    ]
