# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190116_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cakr',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='good',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='goodslste',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goodsname',
            new_name='img',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Goodse',
        ),
    ]
