# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_goodslste_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=100)),
                ('num', models.IntegerField(verbose_name=1)),
            ],
        ),
        migrations.DeleteModel(
            name='goodslste',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
