# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190118_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakr',
            name='num',
        ),
    ]
