# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_cakr_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='img',
            new_name='goodsname',
        ),
        migrations.AddField(
            model_name='cakr',
            name='num',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
