# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190118_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('prices', models.CharField(max_length=10)),
            ],
        ),
    ]
