# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cartt'),
    ]

    operations = [
        migrations.CreateModel(
            name='xiangqing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
