# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermode',
            name='token',
            field=models.IntegerField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
