# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_usermode_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermode',
            name='token',
        ),
    ]
